In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
array_ones = np.ones(10)
array_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
array1 = np.array([2,3])
array1


array([2, 3])

In [ ]:
#for 10 size 0 in array
arrray_zero=np.zeros(10)
arrray_zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
array_zero = np.zeros((4,10))
array_zero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
array_zero.reshape(4,2,5)

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
#for 10 size 1 in array
arrray_ones=np.ones(10)
arrray_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#itteration
for i in array_ones:
   print(i)

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [ ]:
arr1 = np.array([4,7,9])
arr2 = np.array([7,2,5])

arr3 = np.concatenate((arr1,arr2))
arr3.shape

(6,)

In [ ]:
arr3

array([4, 7, 9, 7, 2, 5])

In [ ]:
#for another number we have to print 2 for 10 time then
np.random.choice([2],size=(1,10))

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [ ]:
#suppose I have to mixup number 7,5,3 then 
np.random.choice([5,7,3],size=(1,10))

array([[3, 7, 5, 5, 7, 5, 5, 3, 3, 5]])

In [ ]:
#two dimension array
arr = np.array([[1,2,3,],[4,5,6]])
arr.shape

(2, 3)

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#array indexing
arr[0][1]

2

In [ ]:
#auto two demension array
array_two=np.zeros((3,10))
array_two

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#auto three demension array
#here first 10 ta column ase then 2 ta kore 3 ta ase
array_three=np.zeros((3,2,10))
array_three

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [ ]:
#auto multi demension array

array_multi=np.zeros((3,2,4,10))
array_multi

array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0

In [ ]:
#suppose I have to mixup number 7,5,3 for multi dimension array then
array = np.random.choice([5,7,3],size=(3,7,5))
array

array([[[3, 3, 3, 7, 5],
        [5, 3, 5, 5, 7],
        [3, 5, 3, 5, 3],
        [7, 3, 5, 3, 3],
        [3, 7, 7, 3, 5],
        [5, 5, 5, 7, 7],
        [5, 3, 3, 3, 3]],

       [[7, 7, 7, 7, 7],
        [7, 5, 7, 5, 3],
        [7, 5, 3, 7, 7],
        [7, 3, 3, 3, 7],
        [7, 7, 3, 5, 3],
        [7, 7, 7, 5, 5],
        [3, 7, 5, 3, 7]],

       [[7, 7, 3, 7, 5],
        [7, 3, 5, 7, 5],
        [7, 7, 3, 5, 5],
        [3, 7, 7, 7, 3],
        [3, 5, 3, 5, 7],
        [5, 5, 5, 5, 7],
        [5, 3, 5, 7, 5]]])

In [ ]:
#suppose uporer 3 ta sari theke 2nd sarir 1st column er 3 ber korte chai mean index then
array[1][0][1]

3

In [ ]:
array[2]

array([[5, 5, 3, 7, 3],
       [3, 7, 5, 5, 5],
       [5, 5, 3, 7, 7],
       [7, 7, 7, 5, 3],
       [5, 5, 5, 7, 5],
       [7, 3, 3, 5, 5],
       [7, 5, 5, 5, 3]])

In [ ]:
array[2][3]

array([7, 7, 7, 5, 3])

In [ ]:
array[2][3][1:3]

array([7, 7])